services:
  jupyter_lab:
    build: .
    volumes:
      - /home/ben/BENEDICT_Only:/home/ben/BENEDICT_Only
    ports:
      - "8888:8888"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]