version: '3.8'

services:
  influxdb:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8086:8086"
      - "8089:8089/udp"
    volumes:
      - influxdb_data:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=mydb
      - INFLUXDB_ADMIN_ENABLED=true
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin123
      - INFLUXDB_USER=myuser
      - INFLUXDB_USER_PASSWORD=myuser123

volumes:
  influxdb_data:
    driver: local
