# Use the official InfluxDB image from Docker Hub
FROM influxdb:latest

# Expose port for InfluxDB HTTP API
EXPOSE 8086

# Expose port for InfluxDB UDP service (optional)
EXPOSE 8089

# (Optional) Add any additional configuration or scripts
# COPY influxdb.conf /etc/influxdb/influxdb.conf